// <auto-generated />
namespace DevFestEvent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class addCustomURL2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCustomURL2));
        
        string IMigrationMetadata.Id
        {
            get { return "201402031956385_addCustomURL2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
